# Supabase CLI project configuration
project_id = "hibhfabrnusouqnnzdbv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[auth]
enabled = true
